version: '3.4'

services:
  idp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Th@nhy99
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/idp-imagegallery.pfx
    ports:
      - "5001:443"
    volumes:
      - ./https:/https:ro
    networks:
      - network
    extra_hosts:
      - "idp.imagegallery.com: ${IDP_SERVER}"
      - "api.imagegallery.com: ${API_SERVER}"
      - "sql.imagegallery.com: ${SQL_SERVER}"
      - "client.imagegallery.com: ${CLIENT_SERVER}"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Th@nhy99
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/api-imagegallery.pfx
    ports:
      - "7075:443"
    volumes:
      - ./https:/https:ro
    networks:
      - network
    extra_hosts:
      - "idp.imagegallery.com: ${IDP_SERVER}"
      - "api.imagegallery.com: ${API_SERVER}"
      - "sql.imagegallery.com: ${SQL_SERVER}"
      - "client.imagegallery.com: ${CLIENT_SERVER}"

  client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Th@nhy99
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/client-imagegallery.pfx
    ports:
      - "7184:443"
    volumes:
      - ./https:/https:ro
    networks:
      - network
    extra_hosts:
      - "idp.imagegallery.com: ${IDP_SERVER}"
      - "api.imagegallery.com: ${API_SERVER}"
      - "sql.imagegallery.com: ${SQL_SERVER}"
      - "client.imagegallery.com: ${CLIENT_SERVER}"

  globosql:
    environment:      
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Th@nhy99
    ports:
      - "1433:1433"   
    networks:
      - network

networks:
  network: {}
