version: '3.4'

services:
  idp:
    image: imagegallery-idp:${VERSION}
    container_name: 'idp'
    build:
      context: .
      dockerfile: Marvin.IDP/Dockerfile
    depends_on:
      - placement

  idp-dapr:
    image: "daprio/daprd:edge"
    container_name: 'idp-dapr'
    command: [ "./daprd", "--app-id", "idp", "--app-port", "443", "--placement-host-address", "placement:50006", "--components-path", "/components", "--app-ssl"  ]
    volumes:
        - ./components/:/components:ro
    depends_on:
      - idp
    network_mode: "service:idp" 
    networks:
      - network

  api:
    image: imagegallery-api:${VERSION}
    container_name: 'api'
    build:
      context: .
      dockerfile: ImageGallery.API/Dockerfile
    depends_on:
      - placement

  api-dapr:
    image: "daprio/daprd:edge"
    container_name: 'api-dapr'
    command: [ "./daprd", "--app-id", "api", "--app-port", "443", "--placement-host-address", "placement:50006", "--components-path", "/components", "--app-ssl" ]
    volumes:
        - ./components/:/components:ro
    depends_on:
      - api
    network_mode: "service:api" 

  client:
    image: ${DOCKER_REGISTRY}/imagegallery-client:${VERSION}
    container_name: 'client'
    build:
      context: .
      dockerfile: ImageGallery.Client/Dockerfile
    depends_on:
      - placement

  client-dapr:
    image: "daprio/daprd:edge"
    container_name: 'client-dapr'
    command: [ "./daprd", "--app-id", "client", "--app-port", "443", "--placement-host-address", "placement:50006", "--components-path", "/components", "--app-ssl" ]
    volumes:
        - ./components/:/components:ro
    depends_on:
      - client
    network_mode: "service:client" 
    networks:
      - network

  globosql:
    image: imagegallery-sql:${VERSION}
    container_name: 'globosql'
    build:
      context: .
      dockerfile: mssql/Dockerfile
    restart: always
  
  sqlpad:
    image: sqlpad/sqlpad
    container_name: 'sqlpad'
    environment:
      - SQLPAD_ADMIN=admin
      - SQLPAD_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - network
    extra_hosts:
      - "sql.imagegallery.com: ${SQL_SERVER}"

  redis-commander:
    image: rediscommander/redis-commander
    container_name: 'redis-commander'
    environment:
      - REDIS_HOST=redis-host
      - REDIS_PORT="6379"
      - REDIS_PASSWORD=""
    ports:
      - "8081:8081"
    networks:
      - network

  redis-statestore:
    image: "redis"
    container_name: 'redis-statestore'
    hostname: redis-host
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - placement
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq-host
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network

  placement:
    image: "daprio/dapr"
    container_name: 'placement'
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - network
