version: '3.4'

services:
  idp:
    image: ${DOCKER_REGISTRY}/imagegallery-idp:${VERSION}
    build:
      context: .
      dockerfile: Marvin.IDP/Dockerfile
    depends_on:
      - globosql

  api:
    image: ${DOCKER_REGISTRY}/imagegallery-api:${VERSION}
    build:
      context: .
      dockerfile: ImageGallery.API/Dockerfile
    depends_on:
      - idp

  client:
    image: ${DOCKER_REGISTRY}/imagegallery-client:${VERSION}
    build:
      context: .
      dockerfile: ImageGallery.Client/Dockerfile
    depends_on:
      - idp

  globosql:
    image: ${DOCKER_REGISTRY}/imagegallery-sql:${VERSION}
    build:
      context: .
      dockerfile: mssql/Dockerfile
    restart: always

