version: '3.4'

services:
  idp:
    image: ${DOCKER_REGISTRY}/imagegallery-idp:${VERSION}
    build:
      context: .
      dockerfile: Marvin.IDP/Dockerfile

  api:
    image: ${DOCKER_REGISTRY}/imagegallery-api:${VERSION}
    build:
      context: .
      dockerfile: ImageGallery.API/Dockerfile

  client:
    image: ${DOCKER_REGISTRY}/imagegallery-client:${VERSION}
    build:
      context: .
      dockerfile: ImageGallery.Client/Dockerfile
