apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagegallery-api-app
spec:
  selector:
    matchLabels:
      app: imagegallery-api-app
  replicas: 1
  template:
    metadata:
      labels:
        app: imagegallery-api-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "imagegallery-api"
        dapr.io/app-port: "8083"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"        
    spec:      
      containers:
      - name: imagegallery-api
        image: tmather99/imagegallery-api:v1
        ports:
        - containerPort: 8083
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        imagePullPolicy: Always
        env:
        - name: SEQ_SERVER_URL
          value: "http://seq-service"        
        - name: ASPNETCORE_URLS
          value: "http://*:8083"        
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: SECRET_STORE_NAME
          value: "kubernetes"
          

---
apiVersion: v1
kind: Service
metadata:
  name: imagegallery-api-service
spec:
  selector:
    app: imagegallery-api-app  
  type: ClusterIP  
  ports:
    - protocol: TCP 
      port: 8083
      targetPort: 8083
