apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagegallery-client-app
spec:
  selector:
    matchLabels:
      app: imagegallery-client-app
  replicas: 1
  template:
    metadata:
      labels:
        app: imagegallery-client-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "imagegallery-client"
        dapr.io/app-port: "443"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"        
    spec:      
      hostAliases:
      - ip: "192.168.1.16"
        hostnames:
        - "idp.imagegallery.com"
        - "api.imagegallery.com"
        - "client.imagegallery.com"
      containers:
      - name: imagegallery-client
        image: tmather99/imagegallery-client:v1
        ports:
        - containerPort: 443
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        imagePullPolicy: Always
        env:
        - name: SEQ_SERVER_URL
          value: "http://seq-service"        
        - name: ASPNETCORE_URLS
          value: "http://+:443"        
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "Th@nhy99"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/app/client-imagegallery.pfx"                
        - name: ImageGalleryAPIRoot
          value: "https://api.imagegallery.com"
        - name: IdpServerUri
          value: "https://idp.imagegallery.com"

---
apiVersion: v1
kind: Service
metadata:
  name: imagegallery-client-service
spec:
  selector:
    app: imagegallery-client-app  
  type: ClusterIP  
  ports:
    - protocol: TCP 
      port: 443
      targetPort: 443
