apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagegallery-idp-app
spec:
  selector:
    matchLabels:
      app: imagegallery-idp-app
  replicas: 1
  template:
    metadata:
      labels:
        app: imagegallery-idp-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "imagegallery-idp"
        dapr.io/app-port: "443"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"        
    spec:      
      containers:
      - name: imagegallery-idp
        image: tmather99/imagegallery-idp:v1
        volumeMounts:
        - mountPath: /https
        ports:
        - containerPort: 8083
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        imagePullPolicy: Always
      volumes:
      - name: https
        hostPath:
          path: C:/github/ImageGallery/https
          type: Directory
      env:
        - name: SEQ_SERVER_URL
          value: "http://seq-service"        
        - name: ASPNETCORE_URLS
          value: "http://+:443"        
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "Th@nhy99"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "idp-imagegallery.pfx"        

---
apiVersion: v1
kind: Service
metadata:
  name: imagegallery-idp-service
spec:
  selector:
    app: imagegallery-idp-app  
  type: ClusterIP  
  ports:
    - protocol: TCP 
      port: 5001
      targetPort: 5001
