apiVersion: v1
kind: Secret
metadata:
  name: imagegallery-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/tmather99/ImageGallery.git
