apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 11.8.0
    helm:
      parameters:
        - name: auth.password
          value: admin
        - name: auth.username
          value: admin
        - name: auth.erlangCookie
          value: secretcookie
        - name: replicaCount
          value: '3'
    chart: rabbitmq
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
