name: jedi-ci

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: jedi-ci

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Delete cluster
      run: /usr/local/bin/kind delete cluster --name jedi-ci-cluster

    - name: Create k8s Kind Cluster
      run: |
        /usr/local/bin/kind create cluster --name jedi-ci-cluster --config=k8s/kind/jedi-ci.yml

    - name: Get Cluster status
      run: |
        # wait network is ready
        kubectl wait --for=condition=ready pods --namespace=kube-system -l k8s-app=kube-dns
        kubectl get nodes -o wide
        kubectl get pods -A
