name: jedi-build

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: jedi-ci

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: build images
      run: make build

    - name: push images
      run: make push
